config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :users, only: %i[show edit update]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :bookings, only: %i[index show new create destroy] do
    resources :reviews, only: %i[ new create]
    resources :chatrooms, only: %i[show new create destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:index]

  patch "bookings_update", to: "bookings#update_bookings"

  patch "accept_booking", to: "bookings#accept_booking"
  post "decline_booking", to: "bookings#decline_booking"

  get "error_page", to: "pages#error_page"

  # nest chatrooms in bookings -> every booking has one chatroom
  # /bookings/1/chatroom

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :refugee, class_name: 'User'
  has_one :host, through: :room
  has_one :review
  has_one :chatroom

  validates :arrival_date, presence: true
  validates :departure_date, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/bookings_controller.rb
require 'date'
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    @my_current_bookings = @bookings.select do |booking|
      booking.host.id == current_user.id || booking.refugee_id == current_user.id
    end
    @my_current_bookings = @my_current_bookings.select do |booking|
      (booking.departure_date - Date.today).positive?
    end
    @my_past_bookings = @bookings.select do |booking|
      booking.host.id == current_user.id || booking.refugee_id == current_user.id
    end
    @my_past_bookings = @my_past_bookings.select do |booking|
      (booking.departure_date - Date.today).negative?
    end
  end

  def show
    @review = Review.new
    @booking = Booking.find(params[:id])
    if @booking.status && @booking.status_refugee && @booking.chatroom.nil?
      @chatroom = Chatroom.new
    end
  end

  def new
    if current_user.profile_complete?
      @booking = Booking.new
    else
      flash[:danger] = 'First, we need more information about yourself. Please fill this form.'
      redirect_to edit_user_path(current_user)
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.arrival_date = Date.today
    @booking.departure_date = Date.today + 1
    @booking.refugee_id = current_user.id
    if @booking.refugee.first_name.present? && @booking.refugee.last_name.present? && @booking.refugee.username.present? && @booking.refugee.description.present? && @booking.refugee.identity_number.present? && @booking.refugee.profile_picture.present?
      @booking.room_id = Room.where(host_id: User.where(email: "admin@gmail.com")).first.id
      if @booking.save
        redirect_to bookings_path
      else
        redirect_to error_page_path
      end
    else
      flash[:danger] = 'First, we need more information about yourself. Please fill this form.'
      redirect_to edit_user_path(current_user)
    end
  end

  def update_bookings
    @bookings = Booking.all
    Room.all.each do |room|
      room.update(availability: true)
    end

    @bookings_today = Booking.where(arrival_date: Date.today)
    @bookings_today_desc = @bookings_today.order(beds: :desc)
    @bookings_beds_rating = @bookings_today.left_joins(:review).order("bookings.beds, reviews.rating DESC")
    @rooms_available = Room.where(availability: true)
    @bookings_beds_rating.reverse.each do |booking|
      room_found = find_room(booking, @rooms_available, 0.2)

      if room_found.present? && room_found.instance_of?(Room)
        booking.update(room: room_found)
        room_found.update(availability: false)
      end
    end
    redirect_to bookings_path
  end

  def find_room(booking, rooms, distance)
    @distance = distance
    if @distance <= 10
      if rooms.near(booking.address, @distance).empty?
        find_room(booking, rooms, @distance + 0.2)
        @distance += 0.2

      else
        @result = rooms.near(booking.address, distance).find do |room|
          room.availability && (room.beds - booking.beds) >= 0 && (room.beds - booking.beds) <= 2
        end
        @result
      end
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def accept_booking
    @booking = Booking.find(params[:format])
    @chatroom = Chatroom.new
    @chatroom.booking_id = @booking.id
    @chatroom.name = "Chatroom"
    if current_user.role == "refugee"
      @booking.update(status_refugee: true)
    else
      @booking.update(status: true)
    end
    if @chatroom.save
      redirect_to bookings_path
    else
      raise
    end
  end

  def decline_booking
    @booking = Booking.find(params[:format])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:arrival_date, :departure_date, :beds, :address)
  end

end

app/views/bookings/_chat2_modal.html.erb
<div class="chat-area"></div>
  <nav class = "chat-main-menu">
    <p>CHAT</p>
          <%# Current user is a host %>
        <% if current_user.role == 'host' %>
          <% host_chatrooms = @booking.host.bookings_as_host.map do |booking| %>
          <% booking.chatroom %>
          <% end %>

          <% host_chatrooms.compact.each do |chatroom| %>
            <p class = 'the-chatrooms'><%= link_to "#{current_user.username}", booking_chatroom_path(@booking, chatroom), style: "text-decoration: none; color: black;" %></p>
          <% end %>


          <%# Current user is a refugee %>
         <% else %>
          <% refugee_chatrooms = @booking.refugee.bookings_as_refugee.map do |booking| %>
            <% booking.chatroom %>
          <% end %>

          <% refugee_chatrooms.compact.each do |chatroom| %>
            <p class = 'the-chatrooms'><%= link_to "#{current_user.username}", booking_chatroom_path(@booking, chatroom), style: "text-decoration: none; color: black;"%></p>
          <% end %>


        <% end %>
  </nav>

app/views/bookings/_chat_modal.html.erb
<div class="modal fade" id="chatModal" tabindex="-1" aria-labelledby="chatModalLabel" aria-hidden="true">
  <div class="col-md-2 ms-auto">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="chatModalLabel">Previous chats</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <%# Current user is a host %>
        <% if current_user.role == 'host' %>
          <% host_chatrooms = @booking.host.bookings_as_host.map do |booking| %>
          <% booking.chatroom %>
          <% end %>

          <% host_chatrooms.compact.each do |chatroom| %>

            <p><%= link_to "#{chatroom.booking.refugee.first_name} #{chatroom.booking.refugee.last_name}", booking_chatroom_path(@booking, chatroom), style: "text-decoration: none; color: black;" %></p>
          <% end %>


          <%# Current user is a refugee %>
          <% else %>
            <% refugee_chatrooms = @booking.refugee.bookings_as_refugee.map do |booking| %>
              <% booking.chatroom %>
            <% end %>

              <% refugee_chatrooms.compact.each do |chatroom| %>
                <p><%= link_to "#{chatroom.booking.host.first_name} #{chatroom.booking.host.last_name}", booking_chatroom_path(@booking, chatroom), style: "text-decoration: none; color: black;"%></p>
              <% end %>


          <% end %>
          </div>
        <div class="modal-footer">
          <button type="button" class="universal-button" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
     </div>
  </div>
</div>

app/views/bookings/_images_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="btn-close m-3" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="row">
          <% @booking.room.room_pictures.each do |picture| %>
             <div class="col-8 picture-room" style="background-image: url(<%= cl_image_path @booking.room.room_pictures[0].key %>) ">
              <%#= cl_image_tag @booking.room.room_pictures[0].key %>
             </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_rating_modal.html.erb
<div class="modal fade" id="ratingModal" tabindex="-1" aria-labelledby="ratingModalLabel" aria-hidden="true" data-controller="rating">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ratingModalLabel">Did you had a good time with <%= @booking.refugee.first_name%>?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <div class="container">
        <div class="row justify-content-center">
        <div class="rating-text">
             <p>This rating is never going to be displayed. It is only for organization purposes.</p>
             <p>The people with the best ratings will get rooms assigned first.</p>
        </div>
           <div class="col-12 col-lg-5 pt-3">
             <%= simple_form_for [@booking, @review] do |f|%>
             <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}}, label_html: {class: "text-center w-100"} %>
             <%= f.input :description, placeholder: 'Write your feedback here' %>
             <%= f.button :submit, "Submit", class: "universal-button text-center w-100" %>
             <% end %>
          </div>
        </div>
      </div>
      </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="rooms-index-row h-100 d-flex ms-5">
  <div>
  <% if current_user.email == "admin@gmail.com" %>
    <%= button_to "Create Bookings", bookings_update_path, method: :patch %>
  <% end %>
    <h1 style="padding-left: 40px;">All Bookings</h1>
    <%= render "shared/refugeecardgrid" %>
    <hr class= "hr-line-bookings" style="padding-left:50px">
    <h1 style="padding-left: 40px;">Past Bookings</h1>
    <%= render "shared/pastbookings" %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container-error-edit d-flex justify-content-center col-12 col-sm-4 h-100 w-100 position-relative">
  <%= render "shared/back_button" %>
     <div class = "error-card justify-content-center">
          <h1>Details for Room Tonight</h1>
          <br>
              <%= simple_form_for [@booking] do |f|%>
                  <%= f.input :beds %>
                  <%= f.input :address,
                       input_html: {data: {address_autocomplete_target: "address"}, class: "d-none form-control", required: true },
                        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
                        <br>
                  <%= f.button :submit, "Book", class: "universal-button px-3 py-2" %>
                <% end %>
         </div>
       </div>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="rooms-index-row h-100 d-flex ms-5">

  <div class ="container">
  <% if current_user.role == "host" %>

    <h2 class="booking-show-title" style="padding-left: 50px; color:#FF5D00;"><%= @booking.refugee.first_name%> <%= @booking.refugee.last_name %> <strong>thanks you</strong> for offering a room!</h2>
    <div class="show-profile-link-host d-flex pt-3" style="padding-left: 50px;">
      <i class="fa-regular fa-user ps-1 pe-2"></i><%= link_to "See Profile", user_path(@booking.refugee), class: "btn universal-button" %>
    </div>
  <% else %>
    <h2 class="booking-show-title" style="padding-left: 50px;">Your host for tonight is <%= @booking.host.first_name%> <%= @booking.host.last_name %></h2>
    <div class="show-profile-link-refugee d-flex pt-3" style="padding-left: 50px;">
      <i class="fa-regular fa-user ps-1 pe-2"></i><%= link_to "See Profile", user_path(@booking.host), class: "btn universal-button" %>
    </div>
  <% end %>

  <div class="row">
<div class="col-8 m-5">
  <div class="bookings-images-container position-relative" style="background-image: url(<%= cl_image_path @booking.room.room_pictures.first.key %>)">
      <button type="button" class="room-photo-btn w-100 h-100" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <% if @booking.room.room_pictures %>
          <div class="show-all-photos-btn position-absolute">
            <i class="fa-solid fa-images"> </i> Show All Photos
          </div>
        <% end %>
      </button>
      <div>
          <%= render "bookings/images_modal", booking: @booking %>
      </div>
    </div>
    <div class="booking-info mt-3">

      <% if @booking.host.first_name && @booking.host.last_name %>
        <i class="fa-regular fa-user ps-5 pe-2"></i> Host: <%= @booking.host.first_name + " " + @booking.host.last_name %>
      <% end %>

        <i class="fa-solid fa-calendar ps-5 pe-2"></i><p>Arrival & Departure Dates: <%= @booking.arrival_date %> | <%= @booking.departure_date %></p>
    </div>
    </div>
  <button type="button" id="buttonRating" class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#ratingModal"></button>
    <% if current_user.role == 'host' %>
    <% if @booking.review.nil? && (@booking.departure_date - Date.today).negative? %>
      <%= render "rating_modal" %>
    <% end %>
          </div>
          </div>
    <% end %>
</div>