config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :users, only: %i[show edit update]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :bookings, only: %i[index show new create destroy] do
    resources :reviews, only: %i[ new create]
    resources :chatrooms, only: %i[show new create destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:index]

  patch "bookings_update", to: "bookings#update_bookings"

  patch "accept_booking", to: "bookings#accept_booking"
  post "decline_booking", to: "bookings#decline_booking"

  get "error_page", to: "pages#error_page"

  # nest chatrooms in bookings -> every booking has one chatroom
  # /bookings/1/chatroom

end

app/views/shared/_back_button.html.erb
<button class="back-btn position-absolute d-flex justify-content-center align-items-center" onclick="history.back()">
<%= image_tag "Orange Symbol Invisible left.png" %>&emsp; Go Back</button>

app/views/shared/_cardgrid.html.erb
<div class="grid-cards mt-5">

  <% @rooms.each do |room| %>

    <div class="card-index-room">

      <div class="card-image">
        <% if room.room_pictures.attached? %>
          <%= cl_image_tag room.room_pictures[0].key %>
        <% else %>
          <%= image_tag "https://cdn.britannica.com/22/125622-050-E4DA94ED/Albino-axolotl.jpg", width:200, height:200   %>
        <% end %>
      </div>

      <div class="card-description">
        <li>Host first name: <%= room.host.first_name %></li>
        <li>Host last name: <%= room.host.last_name %></li>
        <li>Amount of beds: <%= room.beds %></li>
      </div>

      <div class="card-link">
        <%= link_to "Show this room", room_path(room) %>
      </div>

    </div>
     <% end %>
</div>

app/views/shared/_chat_modal.html.erb
<div class="modal fade" id="chatModal" tabindex="-1" aria-labelledby="chatModalLabel" aria-hidden="true">
  <div class="col-md-2 ms-auto">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="chatModalLabel">Messages</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

          <%# Current user is a host %>
        <% if current_user.role == 'host' %>
          <% host_chatrooms = current_user.bookings_as_host.map do |booking| %>
          <% booking.chatroom %>
          <% end %>
          <% host_chatrooms.compact.each do |chatroom| %>
            <p><%= link_to "#{current_user.username}", booking_chatroom_path(chatroom.booking, chatroom), style: "text-decoration: none; color: black;" %></p>
          <% end %>


          <%# Current user is a refugee %>
          <% else %>
            <% refugee_chatrooms = current_user.bookings_as_refugee.map do |booking| %>
              <% booking.chatroom %>
            <% end %>
              <% refugee_chatrooms.compact.each do |chatroom| %>
                <p><%= link_to "#{current_user.username}", booking_chatroom_path(chatroom.booking, chatroom), style: "text-decoration: none; color: black;"%></p>
              <% end %>
          <% end %>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn universal-button" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
     </div>
  </div>
</div>

app/views/shared/_chatroomcard.html.erb
<div class="d-flex chatroom-center">
  <div class="container mt-5">
    <% if current_user.role == "host" %>
      <% if current_user.bookings_as_host.each do |booking| %>
        <% if booking.chatroom %>
        <div>
          <p><%= booking.refugee.username %></p>
          <%= link_to "Go to chat", booking_chatroom_path(booking, booking.chatroom) %>
          <hr>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <% end %>
    <% if current_user.role == "refugee" %>
      <% if current_user.bookings_as_refugee.each do |booking| %>
        <% if booking.chatroom %>
          <p><%= booking.host.username%></p>
          <p><%= booking.id %></p>
          <%= link_to "Go to chat", booking_chatroom_path(booking, booking.chatroom) %>
        <% end %>
      <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key == "success" ? "success" : "danger"  %>" style="border-color: #00a2ff; background-color: #dcf1fd; color:#00a2ff;">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="border-div">
    <div class="footer-copyright">
      <p>© 2022 HOST, Inc</p>
    </div>
  </div>
</div>

app/views/shared/_hostcardgrid.html.erb
<div class="grid-cards mt-2">
  <% if @rooms.empty? %>
    <div class="my-2">
      <%= link_to "Add a room", new_room_path, class: "empty-arrays-btn text-decoration-none"%>
    </div>
  <% else %>
  <% @rooms.each do |room| %>

    <div class="card-index-room">

      <div class="card-image">
        <% if room.room_pictures.attached? %>
          <%= cl_image_tag room.room_pictures[0].key, crop: :fill %>
        <% else %>
          <%= image_tag "https://cdn.britannica.com/22/125622-050-E4DA94ED/Albino-axolotl.jpg", width:200, height:200, class: "image-card"   %>
        <% end %>
      </div>

      <div class="card-description">
        <div class="icon-user">
          <i class="fa-solid fa-user pe-2"></i><p><strong>Host:</strong> <%= room.host.first_name %>  <%= room.host.last_name %></p>
        </div>
        <div class="icon-location">
          <i class="fa-solid fa-location-dot pe-2"></i><li><p><%= room.address %></li></p>
        </div>
        <div class="icon-bed">
          <i class="fa-solid fa-bed pe-2"></i> <p><%= room.beds %></p>
        </div>
      </div>

      <div class="card-link">
        <%= link_to "Show room", room_path(room), class: "btn universal-button" %>
      </div>

    </div>
     <% end %>
  <% end %>
</div>

app/views/shared/_interactive_chat.html.erb
<div class ="chat-area"></div>
  <div class = "chat-main-menu">
    <%= image_tag "White Symbol Invisible Up.png", class:"chatbar-logosymbol" %> &nbsp; CHAT
      <% if current_user.role == 'host' %>
        <% host_chatrooms = current_user.bookings_as_host.map do |booking| %>
          <% booking.chatroom %>
        <% end %>
        <% host_chatrooms.compact.each do |chatroom| %>
          <p><strong><%= link_to "#{chatroom.booking.refugee.username}", booking_chatroom_path(chatroom.booking, chatroom), style: "text-decoration: none; color: black;" %></strong></p>
          <% if chatroom.messages.empty? %>
          <% else %>
            <p><%= chatroom.messages.last.content %></p>
          <hr>
          <% end %>
        <% end %>
      <% else %>
        <% refugee_chatrooms = current_user.bookings_as_refugee.map do |booking| %>
          <% booking.chatroom %>
        <% end %>
        <% refugee_chatrooms.compact.each do |chatroom| %>
          <p><strong><%= link_to "#{chatroom.booking.host.username}", booking_chatroom_path(chatroom.booking, chatroom), style: "text-decoration: none; color: black;"%></strong></p>
          <% if chatroom.messages.empty? %>
          <% else %>
            <p><%= chatroom.messages.last.content %></p>
          <hr>
          <% end %>
        <% end %>
      <% end %>
  </div>

app/views/shared/_interactive_sidebar.html.erb
<% if current_user %>
  <div class="area"></div>
    <nav class="main-menu position-absolute">
      <% if current_user.role == 'refugee' %>
        <li class = "iconess">
        <%= image_tag "White Symbol Invisible Right.png", class:"interactive-sidebar-logosymbol" %>
        <i class="fa fa-list fa-2x"></i></li>
      <ul>
        <li>
        <%= link_to bookings_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == bookings_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Dashboard
        <% end %>
        </li>
        <li>
        <% if current_user.bookings_as_refugee.find do |booking| %>
          <% (Date.today - booking.departure_date).negative? %>
          <% end %>
        <% else %>
          <%= link_to new_booking_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == new_booking_url }" do %>
          <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Ask for a room
          <% end %>
        <% end %>
        </li>
        <li>
        <%= link_to chatrooms_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == root_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Messages
        <% end %>
        </li>
      </ul>
      <% else %>
      <li class = "iconess">
      <%= image_tag "White Symbol Invisible Right.png", class:".interactive-sidebar-logosymbol" %>
      <i class="fa fa-list fa-2x"></i></li>
      <ul>
        <li>
        <%= link_to rooms_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == rooms_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Dashboard
        <% end %>
        </li>
        <li>
        <%= link_to new_room_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == new_room_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Add a new room
        <% end %>
        </li>
        <li>
        <%= link_to bookings_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == bookings_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> All bookings
        <% end %>
        </li>
        <li>
        <%= link_to chatrooms_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == root_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Messages
        <% end %>
        </li>
      </ul>
      <% end %>
    </nav>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "OrangeLogoInvisible.png" %>
  <% end %>
  <% if user_signed_in? %>
    <div class="dropdown">
        <button class="dropbtn navbar-user-btn d-flex">
          <%= image_tag "Orange Symbol Invisible down.png", class:"navbar-logodrop" %>
          <i class="fa-regular fa-user p-0"></i>
        </button>
      <div class="dropdown-content text-center">
        <%= link_to user_path(current_user)do %>
            My Profile
        <% end %>
        <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete} %>
        </div>

    </div>
  <% end %>
</div>

app/views/shared/_pastbookings.html.erb
<div class="grid-cards mt-2">

  <% @my_past_bookings.each do |booking| %>
    <div class="card-index-room">
      <div class="card-image">
         <% if booking.room.room_pictures.attached? %>
          <%= cl_image_tag booking.room.room_pictures[0].key, crop: :fill %>
        <% else %>
          <%= image_tag "https://cdn.britannica.com/22/125622-050-E4DA94ED/Albino-axolotl.jpg", width:200, height:200   %>
        <% end %>
      </div>

      <div class="card-description">
        <% if booking.room.host.email == "admin@gmail.com" %>
          <i class="fa-solid fa-user pe-2"></i><p><strong>Host:</strong> Not assigned yet </li>
        <% else %>
        <div class="icon-user">
          <i class="fa-solid fa-user pe-2"></i><p><strong>Host:</strong> <%= booking.host.first_name %> <%= booking.host.last_name %></li>
        </div>
        <div class="icon-calendar">
          <i class="fa-solid fa-calendar pe-2"></i><p><%= booking.departure_date %></p>
        </div>
        <% end %>
      </div>

      <div class="card-link">
        <% if booking.status && booking.status_refugee %>
          <%= link_to "See booking", booking_path(booking), class:"universal-button" %>
        <% end %>
      </div>

      <div class="container">
        <%# Booking is assigned to dumy room %>
        <% if booking.room.host.email == "admin@gmail.com" %>
          <p>Pending...</p>
        <% else %>

        <%# Booking creation has happened, the host / refugee have the ability to accept %>
          <div class="d-flex justify-content-between">
            <% if current_user.role == "refugee" && booking.status_refugee.nil? %>
              <%= button_to "Decline", decline_booking_path(booking), data: {turbo_method: :delete, turbo_confirm:"Are you sure you are not available ?"}, class: "universal-button accept-decline-button px-3 py-2 mb-2" %>
              <%= button_to "Accept", accept_booking_path(booking), method: :patch, class: "universal-button accept-decline-button px-3 py-2 mb-2"  %>
            <% elsif current_user.role == "refugee" && booking.status_refugee && booking.status.nil? %>
              <p>Pending...</p>
            <% end %>
          </div>
          <% end %>
      </div>
      <div class="container">
        <div class="d-flex justify-content-between">
          <% if current_user.role == "host" && booking.status.nil? %>
            <%= button_to "Decline", decline_booking_path(booking), data: {turbo_method: :delete, turbo_confirm:"Are you sure you are not available ?"}, class: "universal-button accept-decline-button px-3 py-2 mb-2" %>
            <%= button_to "Accept", accept_booking_path(booking), method: :patch, class: "universal-button accept-decline-button px-3 py-2 mb-2"%>
          <% elsif current_user.role == "host" && booking.status && booking.status_refugee.nil? %>
          <p>Pending...</p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_refugeecardgrid.html.erb
<div class="grid-cards mt-2">

  <% if @my_current_bookings.empty? %>
    <div class="my-2">
      <% if current_user.role == 'refugee' %>
        <%= link_to "Ask for a room tonight", new_booking_path, class: "empty-arrays-btn text-decoration-none"%>
      <% else %>
      <p>You have no bookings for today yet. If you would like to host someone for the night, make sure that you added a room.</p>
      <% end %>
    </div>
  <% else %>
  <% @my_current_bookings.each do |booking| %>
    <div class="card-index-room">

      <div class="card-image">
         <% if booking.room.room_pictures.attached? %>
          <%= cl_image_tag booking.room.room_pictures[0].key, crop: :fill %>
        <% else %>
          <%= image_tag "https://cdn.britannica.com/22/125622-050-E4DA94ED/Albino-axolotl.jpg", width:200, height:200, class: "image-card" %>
        <% end %>
      </div>

      <div class="card-description">
        <% if booking.room.host.email == "admin@gmail.com" %>
          <i class="fa-solid fa-user pe-2"></i><p><strong>Host:</strong> Not assigned yet </li>
        <% else %>
        <div class="icon-user">
          <i class="fa-solid fa-user pe-2"></i><p><strong>Host:</strong> <%= booking.host.first_name %> <%= booking.host.last_name %></li>
        </div>
        <div class="icon-calendar">
          <i class="fa-solid fa-calendar pe-2"></i><p><%= booking.departure_date %></p>
        </div>
        <% end %>
      </div>

      <div class="card-link">
        <% if booking.status && booking.status_refugee %>
          <%= link_to "See booking", booking_path(booking), class:"btn universal-button" %>
        <% end %>
      </div>

      <div class="container">
        <%# Booking is assigned to dumy room %>
        <% if booking.room.host.email == "admin@gmail.com" %>
          <p>Pending...</p>
        <% else %>

        <%# Booking creation has happened, the host / refugee have the ability to accept %>
          <div class="d-flex justify-content-between">
            <% if current_user.role == "refugee" && booking.status_refugee.nil? %>
              <%= button_to "Decline", decline_booking_path(booking), data: {turbo_method: :delete, turbo_confirm:"Are you sure you are not available ?"}, class: "universal-button accept-decline-button px-3 py-2 mb-2" %>
              <%= button_to "Accept", accept_booking_path(booking), method: :patch, class: "universal-button accept-decline-button px-3 py-2 mb-2"  %>
            <% elsif current_user.role == "refugee" && booking.status_refugee && booking.status.nil? %>
              <p>Pending...</p>
            <% end %>
          </div>
          <% end %>
      </div>
      <div class="container">
        <div class="d-flex justify-content-between">
          <% if current_user.role == "host" && booking.status.nil? %>
            <%= button_to "Decline", decline_booking_path(booking), data: {turbo_method: :delete, turbo_confirm:"Are you sure you are not available ?"}, class: "universal-button accept-decline-button px-3 py-2 mb-2" %>
            <%= button_to "Accept", accept_booking_path(booking), method: :patch, class: "universal-button accept-decline-button px-3 py-2 mb-2"%>
          <% elsif current_user.role == "host" && booking.status && booking.status_refugee.nil? %>
          <p>Pending...</p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<div class="col-2 d-flex flex-column h-100 side-bar">
  <% if current_user %>
    <% if current_user.role == 'refugee' %>
      <%= link_to bookings_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == bookings_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Dashboard
      <% end %>
      <%= link_to new_booking_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == new_booking_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Book Room tonight
      <% end %>
      <%= link_to root_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == root_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Messages
      <% end %>
    <% else %>
      <%= link_to rooms_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == rooms_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Dashboard
      <% end %>
      <%= link_to new_room_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == new_room_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Add new room
      <% end %>
      <%= link_to bookings_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == bookings_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Previous bookings
      <% end %>
      <%= link_to root_path, class: "sidebar-btn mx-3 #{"active-sidebar" if request.original_url == root_url }" do %>
        <%= image_tag "Orange Symbol Invisible right.png", class:"sidebar-logosymbol" %> Messages
      <% end %>
    <% end %>
  <% end %>
</div>