config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :users, only: %i[show edit update]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :bookings, only: %i[index show new create destroy] do
    resources :reviews, only: %i[ new create]
    resources :chatrooms, only: %i[show new create destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:index]

  patch "bookings_update", to: "bookings#update_bookings"

  patch "accept_booking", to: "bookings#accept_booking"
  post "decline_booking", to: "bookings#decline_booking"

  get "error_page", to: "pages#error_page"

  # nest chatrooms in bookings -> every booking has one chatroom
  # /bookings/1/chatroom

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :bookings, dependent: :destroy
  has_many_attached :room_pictures
  geocoded_by :address

  validates :beds, presence: true
  validates :room_pictures, presence: true
  validates :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @rooms = Room.where(host_id: current_user.id)
  end

  def show
  end

  def new
    if current_user.profile_complete?
      @room = Room.new
    else
      flash[:danger] = 'First, we need more information about yourself. Please fill this form.'
      redirect_to edit_user_path(current_user)
    end
  end

  def create
    @room = Room.new(room_params)
    @room.host_id = current_user.id
    if @room.save
      redirect_to rooms_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room), notice: "Room was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:beds, :address, room_pictures: [])
  end
end

app/views/rooms/_room_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="btn-close m-3" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="row">
          <% room.room_pictures.each do |picture| %>
             <div class="col-10 picture-room" style="background-image: url(<%= cl_image_path picture.key %>) ">
              <%#= cl_image_tag @booking.room.room_pictures[0].key %>
             </div>
          <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="container-error-edit d-flex justify-content-center col-12 col-sm-4 h-100 w-100 position-relative">
  <%= render "shared/back_button" %>
     <div class = "error-card justify-content-center">
          <h1>Edit Room</h1>
          <%= simple_form_for @room do |f|%>
            <%= f.input :beds %>
            <%= f.input :room_pictures, as: :file, input_html: { multiple: true }%>
            <%= f.input :address,
               input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
               wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
            <%= f.button :submit, "Edit", class: "universal-button" %>
            <br>
          <% end %>
    </div>
  </div>

</div>

app/views/rooms/index.html.erb
<div class="rooms-index-row h-100 d-flex ms-5">
      <div>
  <% if current_user %>
    <% if current_user.role == 'host' %>
        <h1 style="padding-left: 40px;">Your Rooms</h1>
          <%= render "shared/hostcardgrid" %>
    <% else %>
      <script type="text/javascript">
        window.location.href="/error_page"
      </script>
    <% end %>
  <% end %>

</div>
</div>

app/views/rooms/new.html.erb
<div class="container-error-edit d-flex justify-content-center col-12 col-sm-4 h-100 w-100 position-relative">
  <%= render "shared/back_button" %>
     <div class = "error-card justify-content-center">
        <h1>Add a New Room</h1>
          <%= simple_form_for @room do |f|%>
          <%= f.input :beds %>
          <%= f.input :address,
              input_html: {data: {address_autocomplete_target: "address"}, class: "d-none form-control", required: true },
              wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <%= f.input :room_pictures, as: :file, input_html: { multiple: true } %>
          <br>
          <%= f.button :submit, "Add", class: "universal-button px-3 py-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="rooms-index-row h-100 d-flex ms-5">
<div class="myroom_container", style = "padding-left: 50px;">

  <div class="col-8" style="margin-bottom: 100px">
    <h1>Room located in <%= @room.address %></h1>
    <i class="fa-solid fa-bed mb-3"></i> <%= @room.beds %>
    <% if @room.room_pictures.attached? %>
        <div class="rooms-images-container position-relative" style="background-image: url(<%= cl_image_path @room.room_pictures.first.key %>)">
          <button type="button" class="room-photo-btn w-100 h-100" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <div class="show-all-photos-btn position-absolute">
              <i class="fa-solid fa-images"> </i> Show All Photos
            </div>
          </button>
          <div>
            <%= render "room_modal", room: @room %>
          </div>
        </div>
    <% else %>
      <div class="rooms-images-container" style="background-image: url(https://cdn.britannica.com/22/125622-050-E4DA94ED/Albino-axolotl.jpg)">
    <% end %>
    <div class="rooms-btns d-flex mt-2">
      <%= link_to "Edit", edit_room_path(@room), class: "btn universal-button me-2" %>
      <%= link_to "Remove", room_path(@room), data: { turbo_method: :delete, turbo_confirm: "Are you sure? " }, class: "btn universal-button" %>
    </div>
  </div>
</div>